### ISSUE TITLE
GPU support and environment.yml?

### ISSUE THREAD

**Issue by ricsonc** [CuriousAI/tagger#5]
I am having trouble running the experiments on the GPU inside of the anaconda environment which is installed using the provided install.sh

When I run `THEANO_FLAGS=device=cuda0 python ./runner-shapes50k20x20.py`, then I get the error: 
```
ERROR (theano.sandbox.gpuarray): pygpu was configured but could not be imported
Traceback (most recent call last):
  File "/home/ricson/.conda/envs/tagger/lib/python2.7/site-packages/theano/sandbox/gpuarray/__init__.py", line 20, in <module>
    import pygpu
ImportError: No module named pygpu
```

This would be because `pygpu` is not specified in the `environment.yml` file. Furthermore, installing pygpu 0.7.5 via conda would result in the error:
```
ERROR (theano.sandbox.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/home/ricson/.conda/envs/tagger/lib/python2.7/site-packages/theano/sandbox/gpuarray/__init__.py", line 95, in <module>
    init_dev(config.device)
  File "/home/ricson/.conda/envs/tagger/lib/python2.7/site-packages/theano/sandbox/gpuarray/__init__.py", line 46, in init_dev
    "Make sure Theano and libgpuarray/pygpu "
RuntimeError: ('Wrong major API version for gpuarray:', 2, 'Make sure Theano and libgpuarray/pygpu are in sync.')
```
because it seems like a specific version of pygpu is needed to support theano 0.8.2, and I don't know exactly which version of pygpu is needed.

**Comment by Qwlouse** [comment]
Hey, on my machine it runs without `pygpu` installed. Could you try running with 
`THEANO_FLAGS=device=gpu0 python ./runner-shapes50k20x20.py` (`gpu0` instead of `cuda0`)?

**Comment by ricsonc** [comment]
that appears to fix it, thanks!
